# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e105bbf54ae5b3414127c7fdfa4827c4b93a367275f6b4d3df759d693cd56eb333a6fe63d0ebe5e819758a3038cc0bf45c5a624d740328bc99def82e75d04eb
  aes_password: <%= ENV["EUTW_AES_PASSWORD"] %>

test:
  secret_key_base: 1f2742a8a9878e514d644826cb7cd731e2a48e249576d3d3a4cc2f8d0225d9a2784a70d2cc8780efdfe54ac2b17cfd4b098e41dbdc5e97444102bee90e21c5ee
  aes_password: <%= ENV["EUTW_AES_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aes_password: <%= ENV["EUTW_AES_PASSWORD"] %>
